config.code=123456
config.username=jonas
# No usar acentos en las propiedades ni eñes
config.message=Esto es un mensaje de prueba áéñ
config.listOfValues=valor1,valor2,valor3
config.listOfValues2=valor1,valor2,valor3
config.valuesMap={product:'Cpu Intel i7', price:1200, description:'Procesador Intel i7 12th Gen'}
